name: dyzer
version: 1.0.2
description: Dyzer is a software analytics tool that helps developers analyse and improve software quality. Dyzer is based on a fork of Dart Code Metrics.
repository: https://github.com/msxenon/dyzer

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=7.3.0 <8.0.0"
  analyzer_plugin: ">=0.7.0 <2.0.0"
  ansicolor: ">=2.0.1 <3.0.0"
  args: ">=2.0.0 <3.0.0"
  collection: ">=1.19.0 <3.0.0"
  crypto: ">=3.0.0 <4.0.0"
  file: ">=6.1.1 <8.0.0"
  glob: ">=2.1.0 <4.0.0"
  html: ">=0.15.0 <1.0.0"
  http: ">=1.2.2 <2.0.0"
  meta: ">=1.16.0 <2.0.0"
  path: ">=1.9.0 <2.0.0"
  platform: ">=3.1.0 <4.0.0" 
  pub_updater: ">=0.3.1 <1.0.0"
  source_span: ">=1.9.0 <2.0.0"
  uuid: ">=3.0.0 <5.0.0"
  xml: ">=5.3.0 <8.0.0"
  yaml: ">=3.1.2 <8.0.0"
  equatable: ">=2.0.7 <4.0.0"
  logger: ">=2.6.1 <3.0.0"
  yaml_edit: ">=2.2.2 <3.0.0"

dev_dependencies:
  coverage: ">=1.0.2 <2.0.0"
  intl: ">=0.17.0 <1.0.0"
  lints: ">=2.0.0 <3.0.0"
  mocktail: ">=0.3.0 <1.0.0"
  test: ">=1.25.9 <2.0.0"

  # # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  dyzer:
